import logging
from types import SimpleNamespace

import pytest

from cli.util import (
    extract_layer_count,
    json_key_value,
    normalize_gcode_lines,
    patch_gcode_time,
    resolve_upload_rate_mbps_with_source,
)


def test_json_key_value_parses_number_types_and_strings():
    assert json_key_value("retries=3") == ("retries", 3)
    assert json_key_value("ratio=2.5") == ("ratio", 2.5)
    assert json_key_value("mode=fast") == ("mode", "fast")


def test_json_key_value_rejects_missing_separator():
    with pytest.raises(ValueError, match="key=value"):
        json_key_value("missing-separator")


def test_resolve_upload_rate_prefers_override_over_env_and_config(monkeypatch):
    monkeypatch.setenv("UPLOAD_RATE_MBPS", "25")
    cfg = SimpleNamespace(upload_rate_mbps=5)

    rate, source = resolve_upload_rate_mbps_with_source(config=cfg, override=50)

    assert (rate, source) == (50, "override")


def test_resolve_upload_rate_uses_env_and_logs_invalid_values(monkeypatch, caplog):
    monkeypatch.setenv("UPLOAD_RATE_MBPS", "invalid")
    cfg = SimpleNamespace(upload_rate_mbps=25)

    with caplog.at_level(logging.WARNING):
        rate, source = resolve_upload_rate_mbps_with_source(config=cfg)

    assert (rate, source) == (25, "config")
    assert "Ignoring unsupported UPLOAD_RATE_MBPS='invalid'" in caplog.text


def test_resolve_upload_rate_rejects_invalid_override():
    with pytest.raises(ValueError, match="Unsupported upload rate"):
        resolve_upload_rate_mbps_with_source(override="7")


def test_normalize_gcode_lines_removes_comments_and_blanks():
    gcode = """
    ; generated by slicer
    G28 ; home axes

      G1 X10 Y10
    ; another comment
    M104 S200
    """

    assert normalize_gcode_lines(gcode) == ["G28", "G1 X10 Y10", "M104 S200"]


def test_normalize_gcode_lines_requires_string():
    with pytest.raises(TypeError, match="string"):
        normalize_gcode_lines(None)


def test_patch_gcode_time_inserts_time_before_first_g28():
    data = (
        b"; generated by OrcaSlicer\n"
        b"; estimated printing time = 1h 2m 3s\n"
        b"G28\n"
        b"G1 X10\n"
    )

    patched = patch_gcode_time(data).decode()

    assert ";TIME:3723\nG28\n" in patched
    assert patched.index(";TIME:3723") < patched.index("G28")


def test_patch_gcode_time_keeps_existing_marker():
    data = b";TIME:12\nG28\n"

    assert patch_gcode_time(data) == data


def test_extract_layer_count_reads_header_and_falls_back_to_markers():
    header = b";LAYER_COUNT:42\n; generated by slicer\nG28\n"
    fallback = b"; generated by slicer\nG28\n;LAYER_CHANGE\nG1 X1\n;LAYER_CHANGE\n"

    assert extract_layer_count(header) == 42
    assert extract_layer_count(fallback) == 2
